### ISSUE TITLE
Images Disappear on Save with Classic Editor

### ISSUE THREAD

**Issue by magistro** [mundschenk-at/media-credit#139] opened 2021-07-29 14:46 UTC
Hi Peter. Awesome plugin. We have been using it for several years now. Just recently we noticed an issue when trying to save a post with multiple images. On Saving the post, all images but one were left. See video grab. We disabled all other plugins, except for Classic Editor and changed the theme to default. Latest WordPress install and PHP 7.4. http://recordit.co/Wv0fOVCjNm 
The Gutenberg editor works just fine.  Thanks for the help.

**Comment by mundschenk-at** [comment] 2021-07-29 15:30
Hi @magistro, sorry for the issue. It got reported yesterday by someone else and I've already created a fix locally. I'm not sure why I didn't happen to trigger this while testing. If you send me a message via https://code.mundschenk.at, I can mail you the beta (or I can set up a branch later tonight here on GitHub).

**Comment by magistro** [comment] 2021-07-29 16:31
@mundschenk-at thanks much. Will send you a message.

**Comment by mundschenk-at** [comment] 2021-08-19 12:40
Version 4.2.1 has been released and merged via #140 into the main branch. However, there are reports that the issue still exists even with the modified regex. I am currently investigating this report.

**Comment by mundschenk-at** [comment] 2022-01-25 07:15
@magistro Have you experienced the issue again?

**Comment by magistro** [comment] 2022-01-25 22:39
Nope.

**Comment by mundschenk-at** [comment] 2022-01-25 23:04
Great, then the fix did work as intended. I'll close the ticket then.

**Closed as completed by mundschenk-at** 2022-01-25 23:04 UTC
Labels: bug
